# Generated by Django 3.2.3 on 2021-05-14 15:13

from django.db import migrations, models
import imagesAPI.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=imagesAPI.models.image_file_path)),
            ],
        ),
    ]
