# Generated by Django 3.2.3 on 2021-05-14 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagesAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('body', models.TextField()),
                ('image_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='imagesAPI.image')),
            ],
        ),
    ]
