# Generated by Django 3.2.3 on 2021-05-14 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagesAPI', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='imagefile',
        ),
    ]
